"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['menu.py']
DATA_FILES = ['credentials.json','mlh.py']
OPTIONS = {'argv_emulation': True,
            'plist': {
                'LSUIElement': True,
                    },
            'packages': ['rumps','webbrowser','flask','json','requests'],
            }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
